name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_habits: yes
          plugin_calendar: yes
          config_timezone: America/Fortaleza
